# CMake generated Testfile for 
# Source directory: /Users/burakkurt/Desktop/deep-learning-library-main/tests
# Build directory: /Users/burakkurt/Desktop/deep-learning-library-main/cmake/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[criterion.loss]=] "/Users/burakkurt/Desktop/deep-learning-library-main/cmake/tests/cabernetTests" "--gtest_filter=criterion.loss")
set_tests_properties([=[criterion.loss]=] PROPERTIES  DEF_SOURCE_LINE "criterions.cpp:4" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/share/cmake/Modules/GoogleTest.cmake:516:EVAL;2;add_test;/opt/homebrew/share/cmake/Modules/GoogleTest.cmake:516:EVAL;0;;/opt/homebrew/share/cmake/Modules/GoogleTest.cmake;516;cmake_language;/Users/burakkurt/Desktop/deep-learning-library-main/tests/CMakeLists.txt;7;gtest_add_tests;/Users/burakkurt/Desktop/deep-learning-library-main/tests/CMakeLists.txt;0;")
add_test([=[functions.gradient]=] "/Users/burakkurt/Desktop/deep-learning-library-main/cmake/tests/cabernetTests" "--gtest_filter=functions.gradient")
set_tests_properties([=[functions.gradient]=] PROPERTIES  DEF_SOURCE_LINE "functions.cpp:7" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/share/cmake/Modules/GoogleTest.cmake:516:EVAL;2;add_test;/opt/homebrew/share/cmake/Modules/GoogleTest.cmake:516:EVAL;0;;/opt/homebrew/share/cmake/Modules/GoogleTest.cmake;516;cmake_language;/Users/burakkurt/Desktop/deep-learning-library-main/tests/CMakeLists.txt;7;gtest_add_tests;/Users/burakkurt/Desktop/deep-learning-library-main/tests/CMakeLists.txt;0;")
add_test([=[operations.matmul]=] "/Users/burakkurt/Desktop/deep-learning-library-main/cmake/tests/cabernetTests" "--gtest_filter=operations.matmul")
set_tests_properties([=[operations.matmul]=] PROPERTIES  DEF_SOURCE_LINE "operations.cpp:7" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/share/cmake/Modules/GoogleTest.cmake:516:EVAL;2;add_test;/opt/homebrew/share/cmake/Modules/GoogleTest.cmake:516:EVAL;0;;/opt/homebrew/share/cmake/Modules/GoogleTest.cmake;516;cmake_language;/Users/burakkurt/Desktop/deep-learning-library-main/tests/CMakeLists.txt;7;gtest_add_tests;/Users/burakkurt/Desktop/deep-learning-library-main/tests/CMakeLists.txt;0;")
add_test([=[optimizer.sgd]=] "/Users/burakkurt/Desktop/deep-learning-library-main/cmake/tests/cabernetTests" "--gtest_filter=optimizer.sgd")
set_tests_properties([=[optimizer.sgd]=] PROPERTIES  DEF_SOURCE_LINE "optimizers.cpp:7" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/opt/homebrew/share/cmake/Modules/GoogleTest.cmake:516:EVAL;2;add_test;/opt/homebrew/share/cmake/Modules/GoogleTest.cmake:516:EVAL;0;;/opt/homebrew/share/cmake/Modules/GoogleTest.cmake;516;cmake_language;/Users/burakkurt/Desktop/deep-learning-library-main/tests/CMakeLists.txt;7;gtest_add_tests;/Users/burakkurt/Desktop/deep-learning-library-main/tests/CMakeLists.txt;0;")
